"""Phase 1, Section F — run the test corpus through both models.

Reads backend/test_inputs.json, runs each case through the sentiment and
emotion models (and YAKE if available), and writes a Markdown report to
docs/model-evaluation.md.

This script is reproducible: re-running it overwrites the report.
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path

from transformers import pipeline

try:
    import yake

    YAKE_AVAILABLE = True
    YAKE_ERROR: str | None = None
except Exception as exc:  # noqa: BLE001
    YAKE_AVAILABLE = False
    YAKE_ERROR = f"{type(exc).__name__}: {exc}"

REPO_ROOT = Path(__file__).resolve().parents[2]
CORPUS_PATH = REPO_ROOT / "backend" / "test_inputs.json"
REPORT_PATH = REPO_ROOT / "docs" / "model-evaluation.md"

SENTIMENT_MODEL = "cardiffnlp/twitter-roberta-base-sentiment-latest"
EMOTION_MODEL = "j-hartmann/emotion-english-distilroberta-base"


def top_label(scores: list[dict]) -> tuple[str, float]:
    best = max(scores, key=lambda s: s["score"])
    return best["label"], best["score"]


def fmt_scores(scores: list[dict]) -> str:
    sorted_scores = sorted(scores, key=lambda s: s["score"], reverse=True)
    return ", ".join(f"{s['label']}={s['score']:.3f}" for s in sorted_scores)


def main() -> None:
    corpus = json.loads(CORPUS_PATH.read_text())
    cases = corpus["cases"]

    print(f"Loading sentiment model: {SENTIMENT_MODEL}")
    sentiment = pipeline("text-classification", model=SENTIMENT_MODEL, top_k=None)

    print(f"Loading emotion model: {EMOTION_MODEL}")
    emotion = pipeline("text-classification", model=EMOTION_MODEL, top_k=None)

    yake_extractor = yake.KeywordExtractor(lan="en", n=2, top=5) if YAKE_AVAILABLE else None

    rows: list[dict] = []
    timings: list[float] = []
    for case in cases:
        text = case["text"]
        if not text:
            rows.append(
                {
                    "id": case["id"],
                    "category": case["category"],
                    "text": text,
                    "expected": case["expected_sentiment"],
                    "predicted": "(skipped — empty)",
                    "confidence": 0.0,
                    "sent_breakdown": "(skipped)",
                    "emo_breakdown": "(skipped)",
                    "keywords": "(skipped)",
                    "match": None,
                    "notes": case.get("notes", ""),
                }
            )
            continue

        t0 = time.perf_counter()
        sent_scores = sentiment(text)[0]
        emo_scores = emotion(text)[0]
        dt = time.perf_counter() - t0
        timings.append(dt)

        pred_label, pred_conf = top_label(sent_scores)
        keywords_str = "(yake unavailable)"
        if yake_extractor is not None:
            kws = yake_extractor.extract_keywords(text)
            keywords_str = ", ".join(f"{kw[0]} ({kw[1]:.3f})" for kw in kws) or "(none)"

        rows.append(
            {
                "id": case["id"],
                "category": case["category"],
                "text": text,
                "expected": case["expected_sentiment"],
                "predicted": pred_label,
                "confidence": pred_conf,
                "sent_breakdown": fmt_scores(sent_scores),
                "emo_breakdown": fmt_scores(emo_scores),
                "keywords": keywords_str,
                "match": pred_label == case["expected_sentiment"],
                "notes": case.get("notes", ""),
            }
        )

    # Summary stats — exclude empty-text case from accuracy.
    scored = [r for r in rows if r["match"] is not None]
    correct = sum(1 for r in scored if r["match"])
    accuracy = correct / len(scored) if scored else 0.0
    avg_ms = (sum(timings) / len(timings) * 1000) if timings else 0.0

    by_category: dict[str, list[dict]] = {}
    for r in scored:
        by_category.setdefault(r["category"], []).append(r)

    md: list[str] = []
    md.append("# Model Evaluation — Phase 1\n")
    md.append(
        f"Generated by `backend/explore/evaluate_corpus.py` on "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds').replace('+00:00', 'Z')}.\n"
    )
    md.append("Re-running the script overwrites this file.\n")
    md.append("\n## Summary\n")
    md.append(f"- Sentiment model: `{SENTIMENT_MODEL}`")
    md.append(f"- Emotion model: `{EMOTION_MODEL}`")
    md.append(
        "- Keyword extractor: "
        + ("YAKE" if YAKE_AVAILABLE else f"YAKE **unavailable** — {YAKE_ERROR}")
    )
    md.append(f"- Cases evaluated: {len(scored)} of {len(rows)} (1 empty-string case skipped at the model boundary)")
    md.append(f"- Overall sentiment accuracy: **{correct}/{len(scored)} = {accuracy:.0%}**")
    md.append(f"- Mean per-input inference time (sentiment + emotion combined): {avg_ms:.0f} ms (post-warmup)")
    md.append("")

    md.append("## Accuracy by category\n")
    md.append("| Category | Accuracy |")
    md.append("|---|---|")
    for cat in sorted(by_category):
        cat_rows = by_category[cat]
        cat_correct = sum(1 for r in cat_rows if r["match"])
        md.append(f"| `{cat}` | {cat_correct}/{len(cat_rows)} |")
    md.append("")

    md.append("## Per-case results\n")
    for r in rows:
        match = r["match"]
        if match is None:
            mark = "—"
        elif match:
            mark = "✓"
        else:
            mark = "✗"
        md.append(f"### {r['id']} · `{r['category']}` · {mark}")
        md.append("")
        text_preview = r["text"] if len(r["text"]) <= 200 else r["text"][:200] + "…"
        md.append(f"**Input:** `{text_preview}`" if r["text"] else "**Input:** *(empty string)*")
        md.append("")
        md.append(f"- Expected: `{r['expected']}`")
        md.append(f"- Predicted: `{r['predicted']}` (confidence {r['confidence']:.3f})")
        md.append(f"- Sentiment scores: {r['sent_breakdown']}")
        md.append(f"- Emotion scores: {r['emo_breakdown']}")
        md.append(f"- Keywords: {r['keywords']}")
        if r["notes"]:
            md.append(f"- Notes: {r['notes']}")
        md.append("")

    md.append("## Surprising results / honest weaknesses\n")
    misses = [r for r in scored if not r["match"]]
    if not misses:
        md.append("No misclassifications.")
    else:
        for r in misses:
            text_preview = r["text"] if len(r["text"]) <= 120 else r["text"][:120] + "…"
            md.append(
                f"- **{r['id']}** ({r['category']}): expected `{r['expected']}`, got `{r['predicted']}` "
                f"({r['confidence']:.2f}) — `{text_preview}`"
            )
    md.append("")

    REPORT_PATH.write_text("\n".join(md))
    print(f"\nWrote {REPORT_PATH}")
    print(f"Accuracy: {correct}/{len(scored)} = {accuracy:.0%}")


if __name__ == "__main__":
    main()
